name: App Development Workflow

run-name: Build, upload and install new app version

on: [push]

# adjust if needed and set secret IEM_PW in Github Repo settings
env:
  IEM_URL: "https://iemv2.rcde-fachberatung.de"
  IEM_USER: "iemdemo@gmx.de"
  APP_ID: "5b1d4998406a4682acff1f5008869bb7"
  APP_NAME: "Hello Edge"
  PROJECT_NAME: "CICD-Demoprojekt"
  DEVICE_ID: "09bd8699e9734f918001baf6e61bd499"
  
jobs:
  App-Development-Pipeline:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build app
        run: |
          echo "Start building the application"
          cd app
          docker compose build
          cd ..
      - name: Upload and install app
        run: |
          echo "Initialize IECTL"

          # set enviroment variables
          export IE_SKIP_CERTIFICATE=true
          export EDGE_SKIP_TLS=1

          # create empty folder
          rm -rf workspace
          mkdir workspace

          # add docker engine
          iectl config add publisher --name "publisherdev" --dockerurl "http://127.0.0.1:2375" --workspace "./workspace"

          # init workspace and copy app files
          iectl publisher workspace init

          # add IEM config
          iectl config add iem --name "iemdev" --url "$IEM_URL" --user "$IEM_USER" --password "${{ secrets.IEM_PW }}"

          # get version number
          OLD_VERSION=$(iectl iem app-project app-details --project-name "$PROJECT_NAME" --app-name "$APP_NAME" | jq -r '.versions[0].versionNumber // "0.0.0"')
          # Split the version into an array using '.' as the delimiter
          IFS='.' read -r -a version_parts <<< "$OLD_VERSION"
          # Increment the last part
          version_parts[2]=$((version_parts[2] + 1))
          # Reassemble the version number
          NEW_VERSION="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"
          export NEW_VERSION

          # add new app version
          iectl publisher app-project version create -a "$APP_ID" -v $NEW_VERSION -y ./app/docker-compose.prod.yml -n '{"hello-edge":[{"name":"hello-edge","protocol":"HTTP","port":"80","headers":"","rewriteTarget":"/"}]}' -s 'hello-edge' -t 'FromBoxReverseProxy' -u "hello-edge" -r "/"

          # install new version on device
          iectl  iem app-project install   -a "$APP_NAME"   --version $NEW_VERSION  --info-map "{\"devices\":[\"$DEVICE_ID\"]}"

