name: App Deployment Workflow

run-name: Build and upload new app version

on: [push]

env:
  IEM_URL: "https://192.168.30.4"
  IEM_USER: "johannes.frisch@siemens.com"
  APP_ID: "9c7bca0a2e9f4bc1ab00c8b2dcf43bf7"
  APP_NAME: "CICD-Test"
  DEVICE_ID: "cc7d0c088c43425d968b9f2d760e4229"
  VERSION: v0.0.3
  
jobs:
  App-Deployment-Pipeline:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Step
        run: |
          echo "Start building the application"
          cd app
          docker compose build
          docker images
          cd ..
      - name: Upload Step
        run: |
          echo "Initialize IECTL"

          # set enviroment variables
          export IE_SKIP_CERTIFICATE=true
          export EDGE_SKIP_TLS=1

          # create empty folder
          rm -rf workspace
          mkdir workspace

          # add docker engine
          iectl config add publisher --name "publisherdev" --dockerurl "http://127.0.0.1:2375" --workspace "./workspace"

          # init workspace and copy app files
          iectl publisher workspace init

          # add IEM config
          iectl config add iem --name "iemdev" --url $IEM_URL --user $IEM_USER --password ${{ secrets.IEM_PW }}

          # add new app version
          iectl publisher app-project version create -a $APP_ID -v $VERSION -y ./app/docker-compose.prod.yml -n '{"hello-edge":[{"name":"hello-edge","protocol":"HTTP","port":"80","headers":"","rewriteTarget":"/"}]}' -s 'hello-edge' -t 'FromBoxReverseProxy' -u "hello-edge" -r "/"

          # install new version on device
          iectl  iem app-project install   -a $APP_NAME   --version $VERSION  --info-map '{"devices":["$DEVICE_ID"]}'

      - run: echo "App deploymemt complete"
