name: App Deployment Workflow
run-name: Build and upload new app version
on: [push]
jobs:
  App-Deployment-Pipeline:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Step
        run: |
          echo "Start building the application"
          cd app
          docker compose build
          docker images
          cd ..
      - name: Upload Step
        run: |
          echo "Initialize IECTL"
          # set enviroment variables
          export IE_SKIP_CERTIFICATE=true
          export EDGE_SKIP_TLS=1

      - run: echo "App deploymemt complete"
